# Generated by Django 5.2.17 on 2026-08-18 23:07

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_pokemonspecies_custom_artwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=60)),
                ('collector_title', models.CharField(choices=[('collector', 'Coleccionista'), ('archivist', 'Archivista TCG'), ('illustration', 'Cazador de ilustraciones'), ('completionist', 'Completista'), ('explorer', 'Explorador Cardex')], default='collector', max_length=24)),
                ('motto', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('collecting_since', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1996), django.core.validators.MaxValueValidator(2026)])),
                ('favorite_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('fire', 'Fuego'), ('water', 'Agua'), ('electric', 'Eléctrico'), ('grass', 'Planta'), ('ice', 'Hielo'), ('fighting', 'Lucha'), ('poison', 'Veneno'), ('ground', 'Tierra'), ('flying', 'Volador'), ('psychic', 'Psíquico'), ('bug', 'Bicho'), ('rock', 'Roca'), ('ghost', 'Fantasma'), ('dragon', 'Dragón'), ('dark', 'Siniestro'), ('steel', 'Acero'), ('fairy', 'Hada')], max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='profiles/avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), users.models.validate_profile_image_size])),
                ('accent', models.CharField(choices=[('cyan', 'Cian Dexora'), ('gold', 'Dorado'), ('violet', 'Violeta'), ('green', 'Verde'), ('blue', 'Azul')], default='cyan', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_of_profiles', to='catalog.pokemonspecies')),
                ('featured_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_profiles', to='catalog.tcgcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de coleccionista',
                'verbose_name_plural': 'perfiles de coleccionista',
            },
        ),
    ]
