# Generated by Django 5.2.17 on 2026-08-11 14:36

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCGSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('series', models.CharField(blank=True, db_index=True, max_length=180)),
                ('printed_total', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('symbol_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'expansión TCG',
                'verbose_name_plural': 'expansiones TCG',
                'ordering': ['-release_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_dex_number', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('api_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('generation', models.CharField(blank=True, db_index=True, max_length=30)),
                ('primary_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('secondary_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('external_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'especie Pokémon',
                'verbose_name_plural': 'especies Pokémon',
                'ordering': ['national_dex_number'],
                'indexes': [models.Index(fields=['generation', 'primary_type'], name='catalog_pok_generat_4ef04a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TCGCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('rarity', models.CharField(blank=True, db_index=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=150)),
                ('supertype', models.CharField(blank=True, max_length=50)),
                ('subtypes', models.JSONField(blank=True, default=list)),
                ('types', models.JSONField(blank=True, default=list)),
                ('hp', models.CharField(blank=True, max_length=20)),
                ('remote_image_small', models.URLField(blank=True, max_length=500)),
                ('remote_image_large', models.URLField(blank=True, max_length=500)),
                ('custom_image', models.ImageField(blank=True, upload_to='cards/custom/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.models.validate_image_size])),
                ('image_source', models.CharField(choices=[('automatic', 'Automática'), ('custom', 'Personalizada'), ('placeholder', 'Placeholder')], default='automatic', max_length=20)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ManyToManyField(blank=True, related_name='cards', to='catalog.pokemonspecies')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='catalog.tcgset')),
            ],
            options={
                'ordering': ['-set__release_date', 'name', 'number'],
                'indexes': [models.Index(fields=['is_visible', 'rarity'], name='catalog_tcg_is_visi_9a42e5_idx'), models.Index(fields=['name', 'number'], name='catalog_tcg_name_ca9cb5_idx')],
            },
        ),
    ]
