# Generated by Django 5.2.17 on 2026-08-11 17:27

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='custom_artwork',
            field=models.ImageField(blank=True, upload_to='pokemon/custom/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='remote_artwork_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
