# Generated by Django 5.2.17 on 2026-08-11 14:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('variant', models.CharField(choices=[('standard', 'Estándar'), ('reverse', 'Reverse holo'), ('holo', 'Holo'), ('other', 'Otra')], default='standard', max_length=20)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excelente'), ('good', 'Buena'), ('played', 'Jugada')], default='near_mint', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='catalog.tcgcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'card'], name='collections_user_id_a6e868_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'card', 'variant', 'condition'), name='unique_collection_card_variant_condition')],
            },
        ),
    ]
