# Generated by Django 5.2.17 on 2026-09-30 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_pokemonspecies_custom_artwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='catalog.pokemonspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pokemon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pokémon obtenido',
                'verbose_name_plural': 'Pokémon obtenidos',
                'ordering': ['species__national_dex_number'],
                'indexes': [models.Index(fields=['user', 'species'], name='pokedex_app_user_id_9d425c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'species'), name='unique_owned_species_per_user')],
            },
        ),
    ]
